
export const initialData = [
  {
    id: "LCA-2024-001",
    projectName: "Steel Production Environmental Impact",
    leadAnalyst: "Dr. Sarah Chen",
    department: "Manufacturing",
    startDate: "2024-01-15",
    status: "In Progress",
    progress: 65,
    // Expandable details
    methodology: "ISO 14040:2006",
    functionalUnit: "1 ton of steel",
    systemBoundary: "Cradle to Gate",
    impactCategories: "GWP, AP, EP, ODP, POCP",
    completionDate: "2024-06-30",
    description: "Comprehensive lifecycle assessment of steel production focusing on greenhouse gas emissions and resource depletion.",
  },
  {
    id: "LCA-2024-002",
    projectName: "Cement Production Carbon Footprint",
    leadAnalyst: "Michael Johnson",
    department: "Construction",
    startDate: "2024-02-01",
    status: "Completed",
    progress: 100,
    methodology: "PEF (Product Environmental Footprint)",
    functionalUnit: "1 m³ of concrete",
    systemBoundary: "Cradle to Grave",
    impactCategories: "GWP, Water Use, Land Use",
    completionDate: "2024-05-15",
    description: "Full lifecycle analysis of cement production including end-of-life disposal scenarios.",
  },
  {
    id: "LCA-2024-003",
    projectName: "Aluminum Recycling Analysis",
    leadAnalyst: "Emily Rodriguez",
    department: "Recycling",
    startDate: "2024-03-10",
    status: "In Progress",
    progress: 45,
    methodology: "ISO 14044:2006",
    functionalUnit: "1 kg of recycled aluminum",
    systemBoundary: "Gate to Gate",
    impactCategories: "GWP, ADP, ODP, Energy Consumption",
    completionDate: "2024-08-20",
    description: "Environmental assessment of aluminum recycling processes compared to primary production.",
  },
  {
    id: "LCA-2024-004",
    projectName: "Plastic Packaging Lifecycle Study",
    leadAnalyst: "James Wilson",
    department: "Packaging",
    startDate: "2023-11-20",
    status: "Under Review",
    progress: 90,
    methodology: "ISO 14040:2006",
    functionalUnit: "1000 packaging units",
    systemBoundary: "Cradle to Grave",
    impactCategories: "GWP, POCP, AP, Marine Pollution",
    completionDate: "2024-04-10",
    description: "Detailed study of plastic packaging lifecycle including recycling and waste management scenarios.",
  },
  {
    id: "LCA-2024-005",
    projectName: "Solar Panel Manufacturing Assessment",
    leadAnalyst: "Dr. Lisa Kumar",
    department: "Energy",
    startDate: "2024-01-05",
    status: "In Progress",
    progress: 72,
    methodology: "PEF",
    functionalUnit: "1 kWp installed capacity",
    systemBoundary: "Cradle to Gate",
    impactCategories: "GWP, CED, Water Use, Toxicity",
    completionDate: "2024-07-15",
    description: "Manufacturing phase assessment of photovoltaic solar panels with focus on resource efficiency.",
  },
  {
    id: "LCA-2023-089",
    projectName: "Textile Manufacturing Impact Analysis",
    leadAnalyst: "Robert Martinez",
    department: "Textile",
    startDate: "2023-09-01",
    status: "Completed",
    progress: 100,
    methodology: "ISO 14044:2006",
    functionalUnit: "1 kg of textile product",
    systemBoundary: "Cradle to Grave",
    impactCategories: "GWP, Water Use, Toxicity, Eutrophication",
    completionDate: "2024-01-30",
    description: "Complete lifecycle assessment of textile manufacturing including dyeing and finishing processes.",
  },
  {
    id: "LCA-2024-006",
    projectName: "Electric Vehicle Battery Study",
    leadAnalyst: "Dr. Anna Kowalski",
    department: "Automotive",
    startDate: "2024-02-20",
    status: "Planning",
    progress: 15,
    methodology: "ISO 14040:2006",
    functionalUnit: "1 kWh battery capacity",
    systemBoundary: "Cradle to Gate",
    impactCategories: "GWP, ADP, HTP, Resource Depletion",
    completionDate: "2024-09-30",
    description: "Environmental impact assessment of lithium-ion battery production for electric vehicles.",
  },
  {
    id: "LCA-2024-007",
    projectName: "Paper Production Environmental Profile",
    leadAnalyst: "Thomas Anderson",
    department: "Manufacturing",
    startDate: "2023-12-10",
    status: "Completed",
    progress: 100,
    methodology: "PEF",
    functionalUnit: "1 ton of paper",
    systemBoundary: "Cradle to Grave",
    impactCategories: "GWP, Water Use, AP, EP, Land Use",
    completionDate: "2024-03-25",
    description: "Comprehensive study of paper production including forestry, manufacturing, and end-of-life phases.",
  },
];
