// const initialData = [
//   {
//     documentNo: 1,
//     clientId: "GC-0123-0022",
//     clientName: "A&M International Gen. Cont. L.L.C",
//     projectValue: 12810,
//     service: "EPA",
//     serviceValue: 3810,
//     invoiceRaised: 3810,
//     paymentReceived: 3810,
//     remainingValue: 0,
//     nextServiceAllowed: "✅ Yes",
//     notes: "EPA done, CEMP not required as per Client",
//   },
//   {
//     sno: 2,
//     clientId: "GC-0123-0022",
//     clientName: "A&M International Gen. Cont. L.L.C",
//     projectValue: 12810,
//     service: "CEMP",
//     serviceValue: 9000,
//     invoiceRaised: 0,
//     paymentReceived: 0,
//     remainingValue: 9000,
//     nextServiceAllowed: "❌ No",
//     notes: "Client does not want this service",
//   },
//   {
//     sno: 3,
//     clientId: "GC-0125-0010",
//     clientName: "Orient House for Dev't & Contruction Co",
//     projectValue: 21315,
//     service: "Audit",
//     serviceValue: 6900,
//     invoiceRaised: 6900,
//     paymentReceived: 6900,
//     remainingValue: 0,
//     nextServiceAllowed: "✅ Partial",
//     notes: "03 Audit Pending @2,300 per Audit",
//   },
//   {
//     sno: 4,
//     clientId: "GC-0322-0022",
//     clientName: "The Model Private School",
//     projectValue: 3045,
//     service: "WRR Report",
//     serviceValue: 1450,
//     invoiceRaised: 0,
//     paymentReceived: 0,
//     remainingValue: 1450,
//     nextServiceAllowed: "❌ No",
//     notes: "50% Advance Paid, WRR not required as per client",
//   },
//   {
//     sno: 5,
//     clientId: "GC-0456-0033",
//     clientName: "Sunrise Construction LLC",
//     projectValue: 15000,
//     service: "EPA",
//     serviceValue: 5000,
//     invoiceRaised: 5000,
//     paymentReceived: 5000,
//     remainingValue: 0,
//     nextServiceAllowed: "✅ Yes",
//     notes: "EPA completed, awaiting CEMP approval",
//   },
//   {
//     sno: 6,
//     clientId: "GC-0456-0033",
//     clientName: "Sunrise Construction LLC",
//     projectValue: 15000,
//     service: "CEMP",
//     serviceValue: 10000,
//     invoiceRaised: 0,
//     paymentReceived: 0,
//     remainingValue: 10000,
//     nextServiceAllowed: "❌ No",
//     notes: "Client postponed this service",
//   },
//   {
//     sno: 7,
//     clientId: "GC-0789-0044",
//     clientName: "Delta Real Estate Developers",
//     projectValue: 28000,
//     service: "Audit",
//     serviceValue: 8000,
//     invoiceRaised: 4000,
//     paymentReceived: 4000,
//     remainingValue: 4000,
//     nextServiceAllowed: "✅ Partial",
//     notes: "Second Audit pending",
//   },
//   {
//     sno: 8,
//     clientId: "GC-0789-0044",
//     clientName: "Delta Real Estate Developers",
//     projectValue: 28000,
//     service: "CEMP",
//     serviceValue: 20000,
//     invoiceRaised: 0,
//     paymentReceived: 0,
//     remainingValue: 20000,
//     nextServiceAllowed: "❌ No",
//     notes: "Service not requested yet",
//   },
// ];
